spring:

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  jwt:
    secret: ${SECRET_KEY}
    access_exp: ${ACCESS_EXP}
    refresh_exp: ${REFRESH_EXP}
    access_typ: ${ACCESS_TYP}
    refresh_typ: ${REFRESH_TYP}

server:
  port: ${SERVER_PORT}